### ISSUE TITLE
Inserimento "Indagini puntuali" - Parametro "classe_ind" non funziona 

### ISSUE THREAD

**Issue by Shuffle20** [CNR-IGAG/mzs-tools#37]
Step:
1. inserimento indagine associata ad un sito già inserito
2. Attiva modalità modifica per layer figlio
3. Aggiungi elemento figlio
4. nella finestra di inserimento non è possibile scegliere la Classe dell'indagine (classe_ind)

MzS Tools 1.9.0
QGIS 3.323.0 e 3.34.0
Windows 11 pro 23H2 x64

![error](https://github.com/CNR-IGAG/mzs-tools/assets/55176570/b4a5e547-4df1-414a-8ec3-0e533c0ab1d0)

**Comment by fpennica** [comment]
Sembra un bug di QGIS (>3.28) che riguarda l'editing tramite custom ui con combobox di campi impostati con value relation (succede infatti con qualsiasi altro layer con campi simili, ad esempio Forme).

Non sembrano esserci problemi con l'attuale versione LTR di QGIS (3.28.15), per cui finché non verrà risolto il problema nelle nuove versioni dovrà essere utilizzata la LTR.

**Comment by Shuffle20** [comment]
Grazie mille, procederò con la LTR
m.

**Comment by fpennica** [comment]
Il problema è stato sistemato la settimana scorsa su QGIS, per cui non dovrebbe più ripresentarsi a partire dalle prossime versioni 3.34.x: https://github.com/qgis/QGIS/pull/55964

**Comment by Shuffle20** [comment]
Grazie ancora,
sto lavorando la LTR 3.28.1 e confermo che sembra funzionare tutto.
