### ISSUE TITLE
Custom forms crashing QGIS on Ubuntu

### ISSUE THREAD

**Issue by fpennica** [CNR-IGAG/mzs-tools#4]
This is a [long standing issue](https://issues.qgis.org/issues/8760) of QGIS 2 on Ubuntu. Any custom form (.ui file) will crash QGIS on any Ubuntu version. Unfortunately no resolution has been found yet.

**Comment by Freddi-kru** [comment]
> This is a [long standing issue](https://issues.qgis.org/issues/8760) of QGIS 2 on Ubuntu. Any custom form (.ui file) will crash QGIS on any Ubuntu version. Unfortunately no resolution has been found yet.

Did you solved this problem in any way?

**Comment by fpennica** [comment]
> Did you solved this problem in any way?

Tried a few workarounds mentioned in the issue above, but nothing seems to work...

**Comment by fpennica** [comment]
Luckily this is not an issue anymore with QGIS 3, and the plugin will be ported soon.
